### ISSUE TITLE
Продумать разделение данных для разных календарей

### ISSUE THREAD

**Issue by grebnik89** [art-just-code/sportclub-pet-project#2]
Сделать получение дат аренды на указанные месяцы с количеством арендованных единиц (данные нормализуются в объект, где ключ - дата, значение - количество сапов, причем суммированное, если несколько клиентов сделали заказ на одну и ту же дату)

**Comment by art-just-code** [comment]
2 часть выполнена, первую можно подключить позже, когда будет готов фронтенд для админки

**Comment by art-just-code** [comment]
Логичнее всё же отправлять запросы из самих календарей, так как их отрисовка будет происходить с условием, если месяц еще не прошел
